[package]
name = "interval-map"
version = "0.1.0"
authors = ["kazatsuyu <shirayama.kazatsuyu@gmail.com>"]
edition = "2018"
license = "MIT"
license-file = "LICENSE"

description = "my package description"
readme = "README.md"

[dependencies]
